package lol.vedant.skypvp.api.config;

public class Message {

    public static String HELP_MESSAGE_1 = "GENERAL.HELP_MESSAGE_1";
    public static String HELP_MESSAGE_ADMIN_1 = "GENERAL.HELP_MESSAGE_ADMIN_1";

    public static String KILL_MESSAGE_FORMAT = "KILL_MESSAGE_FORMAT";
    public static String KILL_MESSAGE_VOID = "KILL_MESSAGE_VOID";
    public static String KILL_MESSAGE_PROJECTILE = "KILL_MESSAGE_PROJECTILE";

    public static String PERK_BULLDOZER_TITLE = "MENU.PERK_BULLDOZER_TITLE";
    public static String PERK_EXPERIENCE_TITLE = "MENU.PERK_EXPERIENCE_TITLE";
    public static String PERK_SPEED_TITLE = "MENU.PERK_SPEED_TITLE";
    public static String PERK_JUGGERNAUT_TITLE = "MENU.PERK_JUGGERNAUT_TITLE";

    public static String PERK_BULLDOZER_DESCRIPTION = "MENU.PERK_BULLDOZER_DESCRIPTION";
    public static String PERK_EXPERIENCE_DESCRIPTION = "MENU.PERK_EXPERIENCE_DESCRIPTION";
    public static String PERK_SPEED_DESCRIPTION = "MENU.PERK_SPEED_DESCRIPTION";
    public static String PERK_JUGGERNAUT_DESCRIPTION = "MENU.PERK_JUGGERNAUT_DESCRIPTION";

    public static String PERK_ALREADY_ACTIVE = "MENU.PERK_ALREADY_ACTIVE";
    public static String PERK_PURCHASED_SUCCESSFULLY = "MENU.PERK_PURCHASED_SUCCESSFULLY";
    public static String PERK_EQUIPPED = "MENU.PERK_EQUIPPED";
    public static String NOT_ENOUGH_BALANCE = "MENU.NOT_ENOUGH_BALANCE";


}
